export const events = [
  {
    title: "Innovation Workshop",
    date: "2024-03-20",
    time: "10:00 AM – 4:00 PM",
    location: "Seminar Hall, LBSCEK",
    category: "Workshop",
    shortDescription: "Hands-on session on design thinking and ideation.",
    fullDescription:
      "This workshop provides a practical introduction to innovation methodologies like design thinking, rapid prototyping, and creative problem solving. Ideal for budding innovators and engineering students.",
    image: "/images/events/innovation-workshop.jpg",
    speakers: ["Mr. Arjun Menon", "Ms. Nithya Varma"],
    isPast: true,
  },
  {
    title: "Startup Bootcamp",
    date: "2024-04-10",
    time: "April 10–12, 9:00 AM – 6:00 PM",
    location: "Innovation Lab, LBSCEK",
    category: "Bootcamp",
    shortDescription: "3-day intensive bootcamp on startup building.",
    fullDescription:
      "A 3-day immersive experience covering product-market fit, business modeling, pitching, and MVP development. Participants will work in teams with mentors from the startup ecosystem.",
    image: "/images/events/startup-bootcamp.jpg",
    speakers: ["Dr. Veena Das", "Mr. Anil Joseph"],
    isPast: true,
  },
  {
    title: "Hackathon 2024",
    date: "2024-04-25",
    time: "April 25–27, 9:00 AM – 9:00 PM",
    location: "Main Auditorium, LBSCEK",
    category: "Hackathon",
    shortDescription: "48-hour problem-solving challenge.",
    fullDescription:
      "An exciting 48-hour event where teams develop tech solutions to real-world problems in domains like health, sustainability, and education. Prizes for top 3 teams.",
    image: "/images/events/hackathon-2024.jpg",
    speakers: [],
    isPast: true,
  },
  {
    title: "Pitch Competition",
    date: "2024-05-05",
    time: "11:00 AM – 2:00 PM",
    location: "IEDC Hall, LBSCEK",
    category: "Competition",
    shortDescription: "Pitch your startup idea to expert panel.",
    fullDescription:
      "Selected teams get to pitch their startup ideas to a panel of investors and entrepreneurs. Best pitches get mentoring opportunities and incubation support.",
    image: "/images/events/pitch-competition.jpg",
    speakers: ["Investor Panel", "IEDC Mentors"],
    isPast: true,
  },
  {
    title: "Tech Talk",
    date: "2024-06-15",
    time: "2:00 PM – 3:30 PM",
    location: "Online (Google Meet)",
    category: "Talk",
    shortDescription: "Explore cutting-edge tech trends.",
    fullDescription:
      "A one-hour expert session diving into emerging technologies like AI, Web3, and Robotics. Open to all students and tech enthusiasts.",
    image: "https://images.unsplash.com/photo-1733222765056-b0790217baa9",
    speakers: ["Mr. Akshay Raj", "Ms. Shruthi Prasad"],
    isPast: false,
  },
  {
    title: "Past Event 1",
    date: "2024-01-10",
    time: "10:00 AM – 1:00 PM",
    location: "Room 301, LBSCEK",
    category: "Past",
    shortDescription: "First event of the year on innovation awareness.",
    fullDescription:
      "An orientation and awareness session for freshers to introduce them to the culture of innovation and opportunities within IEDC.",
    image: "/images/events/past-event-1.jpg",
    speakers: ["IEDC Core Team"],
    isPast: true,
  },
  {
    title: "Past Event 2",
    date: "2024-02-05",
    time: "1:00 PM – 3:00 PM",
    location: "Open Stage, LBSCEK",
    category: "Past",
    shortDescription: "Alumni fireside chat on entrepreneurial journeys.",
    fullDescription:
      "Alumni of IEDC LBSCEK share their journey from college to building real-world ventures, including learnings, mistakes, and advice for students.",
    image: "/images/events/past-event-2.jpg",
    speakers: ["Alumni Panel"],
    isPast: true,
  },
];
